# Generated by Django 3.1.7 on 2022-12-30 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='stId',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='cId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
