# Generated by Django 4.1.5 on 2023-01-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20221230_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(choices=[('1', '8:10-9:00'), ('2', '9:10-10:00'), ('3', '10:20-11:10'), ('4', '11:20-12:10'), ('5', '12:20-13:10'), ('6', '13:20-14:10'), ('7', '14:20-15:10'), ('8', '15:30-16:20'), ('9', '16:30-17:20')], max_length=15),
        ),
    ]
